### ISSUE TITLE
Problem flashing the firmware to the STC15-MCU

### ISSUE THREAD

**Issue by mafe** [darrylb123/BetaBlackT5#1]
Hello Darryl,

after compiling your project blackboard-STC15, I am trying to flash the firmware to the STC15 controller, but it does not communicate with it.

```
stcgal -p /dev/ttyUSB0 -P stc15 main.ihx
Waiting for MCU, please cycle power: I/O error: [Errno 5] Input/output error
```

You wrote:
```
Programming the MCU is via a USB to serial converter connected to connector 3P, the BetaBlack MCU programming pins on /dev/ttyUSB0 Modbus communications is via the alternative pins connected to the ESP8266 via jumpers. 
```
Can you give me detailed information on how to wire it correctly, please?

**Comment by darrylb123** [comment]
Sorry, I haven't got my bb with me at the moment.
The connector on the side of the board (3p) is labeled R,G,T which is
receive, ground, transmit. This is the connector for programming the mcu.
Wire the 3.3v usb to serial converter To the bb 3p connector
ground to ground
Receive to T
Transmit to R

With the bb turned off, run stcgal as above then turn on the bb.
After a second or 2 stcgal will display the programming messages.
If that fails, swap the R and T wires

Darryl

**Comment by mafe** [comment]
Thank you Darryl,

it worked like a charm.
I made an wiki page in the repository, which documents the details on wiring.

So long,

Matthias
